version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  snyk: snyk/snyk@0.0.8

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#   E X E C U T O R S:
#   ------------------------------------------------------------------------
#   Executors to run a job with
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

executors:
  # Base image for publishing
  docker-publisher:
    working_directory: ~/barista
    environment:
      WORKSPACE_IMAGE: designops/workspace-base
    docker:
      - image: circleci/buildpack-deps:stretch

  # Base image for workspace agnostic topics
  buildpack:
    working_directory: ~/barista
    docker:
      - image: circleci/buildpack-deps:stretch

  # Base image for building workspace topics
  barista:
    working_directory: ~/barista
    docker:
      - image: circleci/node:lts-buster

  # Base image for building workspace topics
  barista-browsers:
    working_directory: ~/barista
    docker:
      - image: circleci/node:lts-browsers

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#   P A T T E R N S:
#   ------------------------------------------------------------------------
#   Patterns are used to provide reuseable samples of code.
#   This is a yml feature to reduce redundancy.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

filter_forks: &filter_forks
  filters:
    branches:
      # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
      only:
        - /pull\/[0-9]+/

filter_branches: &filter_branches
  filters:
    branches:
      ignore:
        # The cherry picker creates branches where the cherrypick is perfomred
        # Those are instantly failing in circle and should be ignored.
        - /^cherry-pick-.*/
        # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
        - /pull\/[0-9]+/

defaults: &defaults
  working_directory: ~/barista
  docker:
    - image: circleci/node:12


npm_cache: &npm_cache
  keys:
    - npm-packages-{{ checksum "package-lock.json" }}
    - npm-packages-

# The last sha of the branch that holds the previous commit sha.
# could be either master, 4.x or 4.10.x
sha_branch_cache: &sha_branch_cache
  key: last-{{ .Environment.CIRCLE_BRANCH }}-sha

set_env: &set_env
  name: Setup Environment Variables
  command: node dist/libs/workspace/src/scripts/affected-args.js


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#   C O M M A N D S:
#   ------------------------------------------------------------------------
#   Commands that can be used in jobs
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

commands:
  prepare_job:
    description: >-
      Prepares the workspace with the correct working directory and sets the
      affected arguments in the bash environment.
    steps:
      - attach_workspace:
          at: ~/barista
      - run:
          name: Setup Environment Variables
          command:  node dist/libs/workspace/src/scripts/affected-args.js

  skip_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is needed to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Skip job on forked PR."
              circleci step halt
            fi

  setup_bazel_ci:
    description: >-
      Sets up the build cache for Bazel
    steps:
      - attach_workspace:
          at: ~/barista
      - run:
          name: Setup Bazel CI
          command: npm install -G @bazel/bazelisk && cd tools/bazel_build_cache && sh setup_ci_build_cache.sh

  bazel_build:
    description: >-
      Example Bazel build step with cache access
    steps:
      - attach_workspace:
          at: ~/barista
      - run:
          name: Run build
          command: npm run bazel:build

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#   J O B S:
#   ------------------------------------------------------------------------
#   Jobs that can be executed
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

jobs:

# - Builds docker image for workspace
  build-docker-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Registry
          command: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - run:
          name: Build Docker Image
          command: docker build -t $WORKSPACE_IMAGE:latest ./ -f ./.deployment/workspace-base.Dockerfile
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker push $WORKSPACE_IMAGE:latest

# - install npm dependencies
  install:
    executor: barista
    steps:
      - checkout
      - restore_cache:
          <<: *npm_cache
      - run:
          name: Install npm dependencies 🐍
          command: |
            npm ci --ignore-scripts &> /dev/null
            node ./node_modules/.bin/ngcc
      - run:
          name: Build Workspace package 📦
          command: |
            npm run ng run workspace:build
            npm run ng run examples-tools:build
            npm run ng run barista-tools:build
      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/barista
          paths:
            - .

# - sonar checks
  sonar:
    executor: buildpack
    environment:
      # - sonar needs more memory for the scanner run if a LOT of files are changed
      SONAR_SCANNER_OPTS: -Xmx1024m
    steps:
      - skip_for_forked_pull_requests
      - attach_workspace:
          at: ~/barista
      - sonarcloud/scan

# - snyk security checks
  security-checks:
    executor: buildpack
    steps:
      - skip_for_forked_pull_requests
      - attach_workspace:
          at: ~/barista
      - snyk/scan:
          organization: dynatrace-oss

# - check formatting if all files are formatted with prettier
  check-formatting:
    executor: barista
    steps:
      - prepare_job
      - run: yarn nx format:check ${AFFECTED_ARGS} --parallel

# - static codeanalysis of the workspace
  lint-workspace:
    executor: barista
    steps:
      - prepare_job
      - run: ./node_modules/.bin/nx workspace-lint

# - static codeanalysis of the files
  lint:
    executor: barista
    parallelism: 2
    steps:
      - prepare_job
      - run: yarn run-many --target lint

# - static codeanalysis of the style files
  lint-styles:
    executor: barista
    parallelism: 2
    steps:
      - prepare_job
      - run: yarn run-many --target lint-styles

# - build all the packages
  build:
    executor: barista
    resource_class: xlarge
    parallelism: 4
    steps:
      - prepare_job
      - run: yarn run-many --target build --configuration production --increasedMemory 8192 --withDeps
      - persist_to_workspace:
          root: ~/barista
          paths:
            - .

# - pack and upload the build artifacts of the components library
  store-build-artifacts:
    executor: barista
    steps:
      - prepare_job
      - run:
          name: Create components package if it exists
          command: |
            if [[ -d ./dist/libs/components ]];
            then
              cd dist/libs
              tar czf components.tar.gz ./components/
            fi
      - store_artifacts:
          path: dist/libs/components.tar.gz
          destination: barista-components

# - run unit tests
  unit-test:
    executor: barista
    resource_class: large
    parallelism: 3
    steps:
      - prepare_job
      - run: yarn run-many --target test --args="--runInBand"
      - store_test_results:
          path: dist/test-results

# - run end to end tests
  e2e-test-browserstack:
    executor: barista
    resource_class: large
    environment:
      BROWSERSTACK_USE_AUTOMATE: 1
      BROWSERSTACK_DISPLAY_RESOLUTION: 1920x1080
      BROWSERSTACK_TIMEZONE: UTC+1
    steps:
      - prepare_job
      - run: yarn nx affected:e2e ${AFFECTED_ARGS} --configuration=remote-pr
      - store_test_results:
          path: dist/components-e2e

# - run end to end tests
  e2e-test-local:
    executor: barista-browsers
    resource_class: large
    steps:
      - prepare_job
      - run: yarn nx affected:e2e ${AFFECTED_ARGS} --configuration=ci
      - store_test_results:
          path: dist/components-e2e

# - run a11y tests
  a11y:
    executor: barista-browsers
    resource_class: large
    steps:
      - prepare_job
      - run: yarn nx affected --target=a11y ${AFFECTED_ARGS} --parallel --configuration=ci
      - store_test_results:
          path: dist/demos-a11y

# - Execute a small target with Bazel
  bazel_ci:
    executor: barista
    resource_class: medium
    steps:
      - checkout
      - setup_bazel_ci
      - bazel_build

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#   W O R K F L O W S:
#   ------------------------------------------------------------------------
#   Jobs are getting executed through workflows,
#   they are creating the pipeline.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


workflows:
  version: 2.1

# - Publish the workspace image on every master build
  workspace-build:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only: master
          # DOCKERHUB_USER is used for publishing
          # DOCKERHUB_PASSWORD is used for publishing
          context: barista

  fork-check:
    jobs:
      - install:
          <<: *filter_forks
      - check-formatting:
          requires:
            - install
      - lint:
          requires:
            - install
      - lint-workspace:
          requires:
            - install
      - lint-styles:
          requires:
            - install
      - unit-test:
          requires:
            - install
      - build:
          requires:
            - install
      - e2e-test-local:
          requires:
            - install
      - a11y:
          requires:
            - install

# - Runs on every PR check
  pr-check:
    jobs:
      - install:
          <<: *filter_branches
          context: barista
      - check-formatting:
          context: barista
          requires:
            - install
      - sonar:
          # SONAR_TOKEN is needed for sonar cloud checks
          context: barista
          requires:
            - install
      - security-checks:
          # SNYK_TOKEN is needed for security checking
          context: barista
          requires:
            - install
      - lint:
          context: barista
          requires:
            - install
      - lint-styles:
          context: barista
          requires:
            - install
      - lint-workspace:
          context: barista
          requires:
            - install
      - unit-test:
          context: barista
          requires:
            - install
      - e2e-test-browserstack:
          # BROWSERSTACK_ACCESS_KEY is needed for browserstack automation
          # BROWSERSTACK_USERNAME is needed for browserstack automation
          context: barista
          requires:
            - install
      - a11y:
          context: barista
          requires:
            - install
      - build:
          context: barista
          requires:
            - install
      - store-build-artifacts:
          filters:
            branches:
              only: /^([0-9]{1,}\.x|[0-9]{1,}\.[0-9]{1,}\.x|master)$/
          context: barista
          requires:
            - build
      - bazel_ci:
          context: barista
