tasks:
  default:
    build:
      execution_log_binary_file: false
      trigger:
        - test
      pre_cmd:
        - .buildkite/build_cache/setup_ci_build_cache.sh
      bazel_flags:
        - "--keep_going"
      bazel_cmd:
        - "//..."
      post_cmd:
        - bazel shutdown
    test:
      execution_log_binary_file: false
      bazel_flags:
        - "--keep_going"
      bazel_cmd:
        - "//..."
      post_cmd:
        - bazel shutdown
  windows10:
    build:
      disable: false
      trigger:
        - test
      bazel_flags:
        - "--keep_going"
      pre_cmd:
        - bash -c ".buildkite/build_cache/setup_ci_build_cache.sh"
      bazel_cmd:
        - "//..."
      post_cmd:
        - bazel shutdown
    test:
      disable: true
      bazel_flags:
        - "--keep_going"
      bazel_cmd:
        - "//..."
      post_cmd:
        - bazel shutdown
