name: Barista preview

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run:  npm ci

      - name: Build Barista Design System
        run: |
          npm run examples-tools
          npm run barista-tools
          npm run ng build workspace
          npm run ng run barista-design-system:render:production

      - name: ZEIT Now Deployment
        id: now-deployment
        uses: amondnet/now-deployment@v1
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          now-args:
            '--local-config now-preview.json --confirm
            ./dist/apps/barista-design-system/browser'

      - name: Generating Lighthouse Report
        uses: jakejarvis/lighthouse-action@master
        with:
          url: ${{ steps.now-deployment.outputs.preview-url }}

      - name: Save Lighthouse Audit
        uses: actions/upload-artifact@master
        with:
          name: barista-audit
          path: './report'
