name: Barista preview

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: designops/workspace-base:latest
    env:
      WORKSPACE_DIR: /dynatrace
    steps:
      - uses: actions/checkout@v2

      - name: Link the node_modules and the builders in the current working directory
        run : |
          cp -R "$WORKSPACE_DIR/dist/tmp/workspace" "$WORKSPACE_DIR/node_modules/@dynatrace/workspace"
          ln -s "$WORKSPACE_DIR/node_modules" "$PWD/node_modules"

      - name: Build Barista Design System
        run: |
          npm run examples-tools
          npm run barista-tools

          npm run ng run barista-design-system:build:production

      - name: ZEIT Now Deployment
        id: now-deployment
        uses: amondnet/now-deployment@v1
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          now-args:
            '--local-config now-preview.json --confirm
            ./dist/apps/barista-design-system/browser'

      - name: Generating Lighthouse Report
        uses: jakejarvis/lighthouse-action@master
        with:
          url: ${{ steps.now-deployment.outputs.preview-url }}

      - name: Save Lighthouse Audit
        uses: actions/upload-artifact@master
        with:
          name: barista-audit
          path: './report'
