name: Design Tokens UI 🎨

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/design-tokens-ui.yml'
      - '.deployment/design-tokens-ui/**'
      - 'apps/design-tokens-ui/**'
      - 'libs/design-tokens-ui/**'
      - 'libs/shared/design-tokens/**'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Add CI config
        run: mv .github/.bazelrc .bazelrc.user

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/.cache/bazel'
          key: dtui-general-bazel

      - name: Mount Disk cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/.cache/bazel-disk-cache'
          key: dtui-disk-cache-bazel

      - name: Mount Repo cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/.cache/bazel-repo-cache'
          key: dtui-repo-cache-bazel

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Generate Design Tokens
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //libs/shared/design-tokens:build

          npm run copy-generated-tokens
          node tools/shell-helpers/copy-folder.js \
            $(${GITHUB_WORKSPACE}/bin/bazel info bazel-genfiles)/libs/shared/design-tokens/build \
            libs/shared/design-tokens/generated

      - name: Build Design Tokens UI
        run: |
          npm ci
          npm run ng run design-tokens-ui:build:production

      - name: Add Vercel configuration
        run:
          mv ./.deployment/design-tokens-ui/vercel.json
          ./dist/apps/design-tokens-ui/vercel.json

      - name: Vercel Staging Deployment
        if: github.event_name == 'pull_request'
        id: vercel-action-staging
        uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_DESIGN_TOKENS_UI_PROJECT_ID}}
          vercel-args: '--scope dynatrace-oss --confirm ./'
          working-directory: ./dist/apps/design-tokens-ui

      - name: Vercel Production Deployment
        id: vercel-action-production
        if: github.event_name == 'push'
        uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-args: '--prod --scope dynatrace-oss --confirm ./'
          vercel-project-id: ${{ secrets.VERCEL_DESIGN_TOKENS_UI_PROJECT_ID}}
          working-directory: ./dist/apps/design-tokens-ui
