name: "Pull Request Labeler"
on:
  pull_request:
    types: [synchronize, labeled]
jobs:
  pull_request_labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./tools/pull-request-labeler
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
